# This is a basic workflow to help you get started with Actions

name: Telegram message
on: [check_run, check_suite, create, delete, deployment, deployment_status, fork, gollum, issue_comment, issues, label, milestone, page_build, project, project_card, project_column, public, pull_request, pull_request_review, pull_request_review_comment, pull_request_target, push, registry_package, release, status, watch, workflow_run]
jobs:

  notify:
    name: Telegram action notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: New event action [[${{github.event_name}}]::${{ github.event.type}}]::[${{github.actor}}]::[${{github.sha}}]::[${{github.ref}}]
