# This is a basic workflow to help you get started with Actions

name: Telegram message
on: [push, create, delete, issues, label]
jobs:

  notify:
    name: New commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: send custom message with args
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_CHAT }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        args: Action [${{ github.event}}]::[${{github.event_name}}]::[${{github.actor}}]::[${{github.sha}}]::[${{github.ref}}]
